---
title: "Texas Covid Time Series PLots"
author: "The Covid Project and Craig Slinkman"
date: "7/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Texas Covid Data Plots

This RMarkdown document plots the time series data provided by 
[The Covid Project](https://covidtracking.com).

```{r load_packages}
require(tidyverse)                          # I live in the tidyverse ...
require(lubridate)                          # For advanced date processing ...
```
 
## Load required_functions

```{r load_required functions}
source('D:/R-Projects/TexasCovid/functions/get_texas_daily_covid_data.R')
 source('D:/R-Projects/TexasCovid/functions/determine_y_axis_ticks.R')
```

 
## Get the Texas Covid data

We read the data from the Covid Project data.

```{r get_daily_covid_data}

###############################################################################
# We get the covid data using the functions/get_texas_daily_covid_data.
###############################################################################

texas <- get_texas_daily_covid_data()
```

## Positive and negative cummulative cases

These plots shows the positive, negative and total cumulative reported tests.

```{r plot_positive_cases}

#################################################################################
# We compute y-axis tick marks.  Noe that the positive case variable is in the
# third column.
#################################################################################

ticks <- determine_y_axis_ticks( texas, "positive" )

ggplot( texas,
        aes(x = date, y = positive )) +
    geom_line() +
    xlab( "Date" ) +
   scale_y_continuous( "Cumulative positive cases",
                       breaks  = ticks,
                       labels =  ticks )


```

